package abc.grammar;

public enum AbcGrammar {
    MUSIC, HEADER, BODY_ELEMENT,
    // HEADER
    FIELD_NUMBER, FIELD_TITLE, OTHER_FIELDS, FIELD_KEY, FIELD_COMPOSER,
    FIELD_DEFAULT_LENGTH, FIELD_METER, FIELD_TEMPO, FIELD_VOICE,

    KEYNOTE, KEY, KEY_ACCIDENTAL, METER, METER_FRACTION, TEMPO,

    //BODY
    MULTI_VOICE, PART, VOICE_PART, NOTE_LINE,

    //VOICE
    VOICE, SECTION, PHRASE, REPEAT_PHRASE,

    REPEAT, FIRST_REPEAT, SECOND_REPEAT,

    BAR_ELEMENT, BAR_NOTES,

    ELEMENT, NOTE_ELEMENT, TUPLET_ELEMENT, NTH_REPEAT,

    NOTE, MULTI_NOTE, NOTE_OR_REST, NOTE_LENGTH, PITCH, REST,

    ACCIDENTAL, NOTE_SYMBOL, OCTAVE, TUPLET_SPEC,

    // GENERAL
    NOTE_LENGTH_STRICT, BASE_NOTE,

    // AUX
    END_OF_LINE, COMMENT, TEXT, NUMBER, NEWLINE, WHITESPACE, WHITESPACE_ALL,

}
